# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
