# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='locationpoint',
            new_name='point',
        ),
    ]
