# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0002_auto_20170215_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
