# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='order_items',
        ),
    ]
