# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0002_auto_20170210_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='point',
            new_name='locationpoint',
        ),
    ]
