# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0003_carrier_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackersite',
            name='sites',
        ),
        migrations.DeleteModel(
            name='TrackerSite',
        ),
    ]
