# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 09:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0004_remove_customer_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
