# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0006_auto_20161223_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
