# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0011_auto_20161223_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
